Training with a single process on 1 GPUs.
Model resnet50 created, param count: 23507907
Data processing configuration for current model + dataset:
	input_size: (1, 224, 224)
	interpolation: bicubic
	mean: (0.5128,)
	std: (0.2236,)
	crop_pct: 0.875
Traceback (most recent call last):
  File "train.py", line 824, in <module>
    main()
  File "train.py", line 405, in main
    model.cuda()
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Traceback (most recent call last):
  File "train.py", line 824, in <module>
    main()
  File "train.py", line 405, in main
    model.cuda()
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available